FROM debian:13

RUN apt-get update && \
    apt-get install -y openssh-server openssh-client curl && \
    sed -i 's/^#\?\s*PermitRootLogin\s\+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo 'root:root' | chpasswd && \
    curl -sSf https://sshx.io/get | sh && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
